<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Todo.LogService-73ab0624-c58c-4a8b-a0da-7a6d5943aabc</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.17.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Todo.Shared.Contracts\Todo.Shared.Contracts.csproj" />
      <ProjectReference Include="..\Todo.SharedKernel\Todo.SharedKernel.csproj" />
    </ItemGroup>
</Project>
